### ISSUE TITLE
Feature request - set update profile on publisher

### ISSUE THREAD

**Issue by kraduk** [netskopeoss/terraform-provider-netskope#17]
Add ability to set the update profile when creating a publisher via terraform

**Comment by ns-sbrown** [comment]
Thanks for the request. I am hopeful to skope this shortly.

**Comment by mark88d** [comment]
> Thanks for the request. I am hopeful to skope this shortly.

hey, can we get an update please. has progress been made?

**Comment by ns-sbrown** [comment]
I just finished a few fixes and will be working on this next.

**Comment by ns-sbrown** [comment]
Added support for Upgrade profiles in the latest version v0.2.5
