### ISSUE TITLE
Import resources

### ISSUE THREAD

**Issue by stiewie33** [netskopeoss/terraform-provider-netskope#23]
Hi, I am considering using this provider to streamline some processes we're handling manually, however, I can't find any docs regarding importing existing infrastructure. Has anyone imported existing resources before? I'm quite new with terraform so any help would be greatly appreciated.

**Comment by stiewie33** [comment]
@Taoquitok do you have any tips or suggestions on how to connect new apps to existing publishers or is that not possible as I can't get the publishers into my tf state?

**Comment by Taoquitok** [comment]
New private apps with existing publishers should be easy enough as there's a [publishers data source](https://registry.terraform.io/providers/netskopeoss/netskope/latest/docs/data-sources/publishers)

You would need to use the `filter` to limit down to just the one you need, or collect all and use locals or inline logic in the resource to filter down to the appropriate publisher.

I haven't used the data source for publishers so below is an educated guess based on the docs schema for data source + new private all resource, but I'd suspect this either works, or is close to working

```terraform
data "netskope_publishers" "example" {
  filter = "publisher_name your_publisher and registered eq true"
}

resource "netskope_privateapps" "PrivateApp" {
            app_name = "Eaxmple-Private-App"
            host     = "site1.example.internal, site2.example.internal"

            protocols {
                type = "tcp"
                port = "22, 443, 8080-8081"
            }

            protocols {
                type = "udp"
                port = "194"
            }

            publisher {
               # For the data reference, as it's a list of objects at the ".publishers" level
               # I'm assuming you need to [0] index... but you'll need to test to confirm this
                publisher_id   = data.netskope_publishers.example.publishers[0].id
                publisher_name = data.netskope_publishers.example.publishers[0].name
            }
}
```
