### ISSUE TITLE
Feature request: Return publisher list on data.netskope_privateapps

### ISSUE THREAD

**Issue by kraduk** [netskopeoss/terraform-provider-netskope#3]
data netskope_privateapps does not provide a list of publishers bound to this app. This is critical information when wanting to bind a new publisher to the app. Alternatively we could another function to return this data

eg 
data.netskope_privateapps_pubishers

**Comment by ns-sbrown** [comment]
Thank you for this feature request. I will review this and see what we can do.

**Comment by ns-sbrown** [comment]
Investigating including "service_publisher_assignments" which the API returns now. If I can make it work, I will include it it my next update.

**Comment by ns-sbrown** [comment]
In the latest version(v0.2.5) includes "service_publisher_assignments" in the private apps resource.
