### ISSUE TITLE
Feature request: Bind publisher to private app

### ISSUE THREAD

**Issue by kraduk** [netskopeoss/terraform-provider-netskope#4]
No scope in the provider to bind a publisher to a private app, currently we have to fall back to the API which is suboptimal

eg
resource Private_app_add_publisher {
  app_id = string
  publisher_id = string
}

the inverse would be good as well for when a publisher is torn down
resource Private_app_remove_publisher {
  app_id = string
  publisher_id = string
}

**Comment by ns-sbrown** [comment]
I will review this but likely we will need to rely on Publisher tagging which you have also requested.

https://github.com/netskopeoss/terraform-provider-netskope/issues/5

**Comment by kraduk** [comment]
From our conversations it does appear it will

**Comment by ns-sbrown** [comment]
Closing this as it will be addressed with [https://github.com/netskopeoss/terraform-provider-netskope/issues/5](https://github.com/netskopeoss/terraform-provider-netskope/issues/5)
